### ISSUE TITLE
TypeError when reading input files

### ISSUE THREAD

**Issue by JiahuiSophieHU** [zhaoxy92/GLaRA#1]
Hi, 
How do you convert NCBI txt files to pickle?
Can you please share the code to create pickle files? 
Thanks in advance, 

GLaRA/code-NCBI$ python prepare_candidates_and_embeddings.py --dataset LaptopReview --rule_type SurfaceForm
Train:  14472
Dev:  3901
Test:  3901
Running on the GPU
Traceback (most recent call last):
  File "prepare_candidates_and_embeddings.py", line 81, in <module>
    pos_cnt += collect_POS(sent, label='I')
  File "/home/sophie/Documents/Thesis/My_Expe/NER/GLaRA/code-NCBI/utils_prepare_data.py", line 34, in collect_POS
    tokens, tags = sentence['tokens'], sentence['tags']
TypeError: string indices must be integers

**Comment by JiahuiSophieHU** [comment]
what do 'tokens' and 'tags" represent?

**Comment by JiahuiSophieHU** [comment]
And what do  'tags' mean please?

**Comment by zhaoxy92** [comment]
Hi, the script for caching data to pickle is uploaded now. Please note that I cache data into pickle purely for a faster loading to avoid loading from the original text into data objects every time. To get the data objects to cache, you will have to install the dependencies in the requirement file because the data objects come from the LinkedHMM work that our work is built on. I'm closing this issue now, feel free to reach out if there is more questions. Thanks.
